Db:
  ConnectionString:
    settings-key: Hftv2Service-Db-ConnectionString
Auth:
  JwtSecret:
    settings-key: Hftv2Service-Auth-JwtSecret
  LykkeAud:
    settings-key: Hftv2Service-Auth-LykkeAud
Services:
  AssetsServiceUrl:
    settings-key: AssetsServiceUrl
 Cache:
    AssetsCacheDuration:
      settings-key: Hftv2Service-Cache-AssetsCacheDuration
