RabbitMq:
  ConnectionString:
    settings-key: SagasRabbitMqConnStr
    types: [RabbitMq]
  MeConnectionString:
    settings-key: MatchingEngine-OrderBookRabbit
    types: [RabbitMq]
  ExchangeName:
    settings-key: Hftv2Service-RabbitMq-HftInternalExchangeName
  OrderbooksExchangeName:
    settings-key: Hftv2Service-RabbitMq-OrderbooksExchangeName
  BalancesExchangeName:
    settings-key: Hftv2Service-RabbitMq-BalancesExchangeName
MyNoSqlServer:
  ReaderServiceUrl:
    settings-key: MyNoSqlServer-ReaderUrl
  WriterServiceUrl:
    settings-key: MyNoSqlServer-WriterUrl
  TickersTableName:
    settings-key: MyNoSqlServer-TickersTableName
  PricesTableName:
    settings-key: MyNoSqlServer-PricesTableName
  OrderbooksTableName:
    settings-key: MyNoSqlServer-OrderbooksTableName
  BalancesTableName:
    settings-key: MyNoSqlServer-BalancesTableName
ElasticsearchLogs:
  NodeUrls:
    settings-key: ElasticSearch-NodeUrls
    types: [JsonArray]
  IndexPrefixName:
    settings-key: ElasticSearch-IndexPrefixName
Serilog:
  minimumLevel:
    default:
      settings-key: Hftv2Worker-Serilog-DefaultMinLevel
    override:
      settings-key: Hftv2Worker-Serilog-Override
      types: [Json]
