Auth:
  JwtSecret:
    settings-key: Hftv2Service-Auth-JwtSecret
  LykkeAud:
    settings-key: Hftv2Service-Auth-LykkeAud
Services:
  AssetsServiceUrl:
    settings-key: AssetsServiceUrl
  MarketDataGrpcServiceUrl:
    settings-key: MarketDataGrpcServiceUrl
  HistoryServiceUrl:
    settings-key: HistoryServiceUrl
  BalancesServiceUrl:
    settings-key: BalancesServiceUrl
  HftInternalServiceUrl:
    settings-key: HftInternalServiceUrl
Cache:
  AssetsCacheDuration:
    settings-key: Hftv2Service-Cache-AssetsCacheDuration
Redis:
  RedisConfiguration:
    settings-key: HFT-RedisConfiguration
  InstanceName:
    settings-key: OrderBooks-CacheInstance
  OrderBooksCacheKeyPattern:
    settings-key: OrderBooks-CacheKeyPattern
MatchingEngine:
  Host:
    settings-key: MatchingEngine-Host
  Port:
    settings-key: MatchingEngine-Port
RabbitMq:
  ConnectionString:
    settings-key: SagasRabbitMqConnStr
    types: [RabbitMq]
  MeConnectionString:
    settings-key: MatchingEngine-OrderBookRabbit
    types: [RabbitMq]
  ExchangeName:
    settings-key: Hftv2Service-RabbitMq-HftInternalExchangeName
  OrderbooksExchangeName:
    settings-key: Hftv2Service-RabbitMq-OrderbooksExchangeName
  BalancesExchangeName:
    settings-key: Hftv2Service-RabbitMq-BalancesExchangeName
  OrdersExchangeName:
    settings-key: Hftv2Service-RabbitMq-OrdersExchangeName
MyNoSqlServer:
  ReaderServiceUrl:
    settings-key: MyNoSqlServer-ReaderUrl
  WriterServiceUrl:
    settings-key: MyNoSqlServer-WriterUrl
  TickersTableName:
    settings-key: MyNoSqlServer-TickersTableName
  PricesTableName:
    settings-key: MyNoSqlServer-PricesTableName
  OrderbooksTableName:
    settings-key: MyNoSqlServer-OrderbooksTableName
  BalancesTableName:
    settings-key: MyNoSqlServer-BalancesTableName
  OrdersTableName:
    settings-key: MyNoSqlServer-OrdersTableName
  TradesTableName:
    settings-key: MyNoSqlServer-TradesTableName
ElasticsearchLogs:
  NodeUrls:
    settings-key: ElasticSearch-NodeUrls
    types: [JsonArray]
  IndexPrefixName:
    settings-key: ElasticSearch-IndexPrefixName
Serilog:
  minimumLevel:
    default:
      settings-key: Hftv2Service-Serilog-DefaultMinLevel
    override:
      settings-key: Hftv2Service-Serilog-Override
      types: [Json]
