Db:
  ConnectionString:
    settings-key: Hftv2Service-Db-ConnectionString
Auth:
  JwtSecret:
    settings-key: Hftv2Service-Auth-JwtSecret
  LykkeAud:
    settings-key: Hftv2Service-Auth-LykkeAud
Services:
  AssetsServiceUrl:
    settings-key: AssetsServiceUrl
Cache:
  AssetsCacheDuration:
    settings-key: Hftv2Service-Cache-AssetsCacheDuration
Redis:
  RedisConfiguration:
    settings-key: HFT-RedisConfiguration
  InstanceName:
    settings-key: OrderBooks-CacheInstance
  OrderBooksCacheKeyPattern:
    settings-key: OrderBooks-CacheKeyPattern
